### ISSUE TITLE
error: Invalid value for '<binary>': /input is not a file.

### ISSUE THREAD

**Issue by frakman1** [fkie-cad/cwe_checker#218]
Due to recent changes to this docker image, the previous method of running this tool is now failing with this error:

```
error: Invalid value for '<binary>': /input is not a file.
```

To make matters worse, there is no history of tags on dockerhub to use a previous working version.

I found a workaround by overriding the entrypoint. Trickier to do within a Gitlab (`gitlab-ci.yml`) pipeline but also possible.
I also found that `cwe_checker` no longer works if called within docker and the full path must now be specified (`/home/cwe/cwe_checker`)

It would be nice if:
1- Changes were not breaking or backward incompatible.
2- If they have to be, then at least a previous tag be made available to maintain historical behavior.

However, since I wish to use the latest iteration of this tool, it would be nice to be able to use it consistently.

For context, this is my current gitlab job specification:

```yaml
.cwechecker: &cwechecker
  stage: cwechecker
  image: fkiecad/cwe_checker:stable
  allow_failure: true
  before_script:
    - <removed>
  script:
    - set +e
    - cd xxx/rootfs/
    - for filename in $(cut -d':' -f1 <<< "$(find . -type f -exec file {} + | grep ELF)") ; do echo "#######" ; ls $filename ; echo "#######" ; cwe_checker "$filename" ; done | tee cwechecker-results.txt
    - cd -
    - cp xxx/rootfs/cwechecker-results.txt output/
    - set -e
  artifacts:
    name: <removed>
    paths:
      - output/cwechecker-results.txt
    expire_in: 3 days
```

For completeness, the workaround was adding:
```yaml
entrypoint: [""]
```
under the line with the `image:` keyword
